# Generated by Django 3.2.18 on 2023-07-07 11:10

from django.db import migrations, models
import django.utils.timezone
import django_summernote.fields
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20230629_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.CharField(default=main.models.property_id, max_length=6, primary_key=True, serialize=False)),
                ('activate', models.BooleanField(default=False)),
                ('from_admin', models.BooleanField(default=False)),
                ('name', models.CharField(default='Bomach admin', max_length=250)),
                ('phone', models.CharField(default='N/A', max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('slug', models.CharField(blank=True, max_length=250, unique=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('location', models.CharField(max_length=500)),
                ('content', django_summernote.fields.SummernoteTextField()),
                ('priority', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
            bases=(main.models.CustomBaseModel, models.Model),
        ),
    ]
