# Generated by Django 3.2.18 on 2023-07-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20230710_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertycoordinates',
            old_name='x',
            new_name='east',
        ),
        migrations.RenameField(
            model_name='propertycoordinates',
            old_name='y',
            new_name='lat',
        ),
        migrations.AddField(
            model_name='propertycoordinates',
            name='lon',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertycoordinates',
            name='north',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
