# Generated by Django 3.2.18 on 2023-07-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20230711_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycoordinates',
            name='lat_dms',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertycoordinates',
            name='lon_dms',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
