# Generated by Django 3.2.18 on 2023-07-12 07:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20230711_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('priority', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=250)),
                ('priority', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=(models.Model, main.models.ImageUrl),
        ),
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.AddField(
            model_name='property',
            name='property_title',
            field=models.CharField(default='Title', max_length=250),
        ),
        migrations.AlterField(
            model_name='property',
            name='email',
            field=models.EmailField(default='bomachgroupmanagement@gmail.com', max_length=250),
        ),
        migrations.AlterField(
            model_name='property',
            name='phone',
            field=models.CharField(default='080 3665 6173', max_length=250),
        ),
        migrations.AlterField(
            model_name='propertycoordinates',
            name='lat',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='propertycoordinates',
            name='lat_dms',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='propertycoordinates',
            name='lon',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='propertycoordinates',
            name='lon_dms',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='SubPropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('priority', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('property_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.propertycategory')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_images',
            field=models.ManyToManyField(to='main.PropertyImage'),
        ),
        migrations.AddField(
            model_name='property',
            name='sub_property_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subpropertycategory'),
        ),
    ]
