# Generated by Django 3.2.18 on 2023-07-12 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20230712_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertycategory',
            options={'verbose_name': 'Property Category', 'verbose_name_plural': 'Property Categories'},
        ),
        migrations.AlterModelOptions(
            name='subpropertycategory',
            options={'verbose_name': 'Sub Property Category', 'verbose_name_plural': 'Sub Property Categories'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_images',
        ),
        migrations.AddField(
            model_name='propertycoordinates',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.property'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.property'),
        ),
    ]
