# Generated by Django 3.2.18 on 2025-03-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_propertycoordinates_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='conclusion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dervdezl1/image/upload/v1/media/images/Bomach_Cover_Photo_pvm7zp', upload_to='images/'),
            preserve_default=False,
        ),
    ]
