# Generated by Django 3.2.18 on 2025-03-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20250306_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contact_us_heading',
            field=models.TextField(default='If you Have Any Query, Don’t Hesitate Contact with us'),
        ),
    ]
