# Generated by Django 3.2.18 on 2025-04-14 11:53

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_property_contact_us_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='content',
            field=django_summernote.fields.SummernoteTextField(max_length=10000000),
        ),
    ]
