# Generated by Django 3.2.18 on 2025-10-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_bulksms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulksms',
            name='recipients',
            field=models.TextField(help_text='Comma-separated list of recipient phone numbers. 234901234567,2348012345678'),
        ),
    ]
