# Generated by Django 3.2.18 on 2025-11-03 08:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_summernote.fields
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_bulksms_recipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.CharField(blank=True, max_length=250, unique=True)),
                ('location', models.CharField(max_length=250)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=100)),
                ('salary_range', models.CharField(blank=True, help_text='e.g. ₦100,000 - ₦200,000', max_length=250, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', django_summernote.fields.SummernoteTextField()),
                ('requirements', django_summernote.fields.SummernoteTextField()),
                ('responsibilities', django_summernote.fields.SummernoteTextField()),
                ('benefits', django_summernote.fields.SummernoteTextField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-priority', '-date'],
            },
            bases=(main.models.CustomBaseModel, models.Model, main.models.ImageUrl),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=250)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('message', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.job')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-applied_at'],
            },
        ),
    ]
