# Generated by Django 3.2.18 on 2025-11-03 08:18

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_job_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='benefits',
            field=django_summernote.fields.SummernoteTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=django_summernote.fields.SummernoteTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=django_summernote.fields.SummernoteTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=django_summernote.fields.SummernoteTextField(blank=True, default='', null=True),
        ),
    ]
